// Mocks generated by Mockito 5.4.6 from annotations
// in savings_goals/test/core/data/repositories/savings_goals_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:savings_goals/src/core/data/datasource/savings_goals_remote_datasource.dart'
    as _i3;
import 'package:savings_goals/src/core/data/models/create_savings_goal_request_model.dart'
    as _i5;
import 'package:savings_goals/src/core/data/models/savings_goal_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSavingsGoalModel_0 extends _i1.SmartFake
    implements _i2.SavingsGoalModel {
  _FakeSavingsGoalModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SavingsGoalsRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavingsGoalsRemoteDatasource extends _i1.Mock
    implements _i3.SavingsGoalsRemoteDatasource {
  @override
  _i4.Future<List<_i2.SavingsGoalModel>> fetchGoals(String? childId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGoals, [childId]),
            returnValue: _i4.Future<List<_i2.SavingsGoalModel>>.value(
              <_i2.SavingsGoalModel>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i2.SavingsGoalModel>>.value(
                  <_i2.SavingsGoalModel>[],
                ),
          )
          as _i4.Future<List<_i2.SavingsGoalModel>>);

  @override
  _i4.Future<_i2.SavingsGoalModel> createGoal(
    String? childId,
    _i5.CreateSavingsGoalRequestModel? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createGoal, [childId, request]),
            returnValue: _i4.Future<_i2.SavingsGoalModel>.value(
              _FakeSavingsGoalModel_0(
                this,
                Invocation.method(#createGoal, [childId, request]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SavingsGoalModel>.value(
              _FakeSavingsGoalModel_0(
                this,
                Invocation.method(#createGoal, [childId, request]),
              ),
            ),
          )
          as _i4.Future<_i2.SavingsGoalModel>);

  @override
  _i4.Future<_i2.SavingsGoalModel> updateProgress(
    String? goalId,
    double? amount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProgress, [goalId, amount]),
            returnValue: _i4.Future<_i2.SavingsGoalModel>.value(
              _FakeSavingsGoalModel_0(
                this,
                Invocation.method(#updateProgress, [goalId, amount]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SavingsGoalModel>.value(
              _FakeSavingsGoalModel_0(
                this,
                Invocation.method(#updateProgress, [goalId, amount]),
              ),
            ),
          )
          as _i4.Future<_i2.SavingsGoalModel>);

  @override
  _i4.Future<void> deleteGoal(String? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGoal, [goalId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
